use std::{
    borrow::Cow,
    fs,
    io::Cursor,
    path::{Component, Path},
    sync::OnceLock,
};

use anyhow::{Context, Result, bail};
use pulldown_cmark::{CodeBlockKind, CowStr, Event, Options, Parser, Tag, TagEnd, html};
use syntect::{
    highlighting::{Theme, ThemeSet},
    html::highlighted_html_for_string,
    parsing::SyntaxSet,
};

#[derive(Debug, Clone)]
pub struct DeckDocument {
    pub slides: Vec<Slide>,
}

#[derive(Debug, Clone)]
pub struct Slide {
    pub html: String,
    /// Number of sequential paragraph/list-item reveals in the slide body.
    pub reveal_count: usize,
    pub interaction: Option<Interaction>,
    pub notes: Option<String>,
    pub iframe_assets: Vec<String>,
    /// Rendered Mermaid sources, slide body first and then presenter notes.
    pub mermaid_diagrams: Vec<String>,
}

impl Slide {
    /// Render steps `1..=step` as visible, retaining layout for later steps.
    ///
    /// Step zero marks every reveal pending; steps at or beyond `reveal_count`
    /// borrow the fully visible base HTML. Presenter notes are never changed.
    pub fn html_at_step(&self, step: usize) -> Cow<'_, str> {
        if step >= self.reveal_count {
            return Cow::Borrowed(&self.html);
        }

        let mut output = String::with_capacity(self.html.len());
        let mut copied = 0;
        // Only these exact opening tags are generated by the Markdown renderer.
        // Raw HTML and attribute values are escaped before reaching this point.
        for (offset, _) in self.html.match_indices('<') {
            let tag = &self.html[offset..];
            let Some(rest) = tag
                .strip_prefix("<p data-reveal-step=\"")
                .or_else(|| tag.strip_prefix("<li data-reveal-step=\""))
            else {
                continue;
            };
            let Some((number, _)) = rest.split_once("\">") else {
                continue;
            };
            if number.parse::<usize>().is_ok_and(|number| number > step) {
                let end = offset + tag.len() - rest.len() + number.len() + 1;
                output.push_str(&self.html[copied..end]);
                output.push_str(" data-reveal-pending aria-hidden=\"true\" inert");
                copied = end;
            }
        }
        output.push_str(&self.html[copied..]);
        Cow::Owned(output)
    }
}

#[derive(Debug, Clone)]
pub enum Interaction {
    Poll {
        question: Option<String>,
        options: Vec<String>,
        multiple: bool,
        orientation: ChartOrientation,
    },
    WordCloud {
        prompt: String,
        max_length: usize,
    },
    Quiz {
        question: String,
        options: Vec<QuizOption>,
    },
    Ordering {
        prompt: String,
        options: Vec<String>,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChartOrientation {
    Horizontal,
    Vertical,
}

#[derive(Debug, Clone)]
pub struct QuizOption {
    pub label: String,
    pub correct: bool,
}

pub fn parse_deck(source: &str) -> Result<DeckDocument> {
    let raw_slides = split_slides(source);
    if raw_slides.is_empty() {
        bail!("A deck needs at least one slide");
    }

    let slides = raw_slides
        .into_iter()
        .enumerate()
        .map(|(index, source)| {
            parse_slide(source, index).with_context(|| format!("slide {}", index + 1))
        })
        .collect::<Result<Vec<_>>>()?;

    Ok(DeckDocument { slides })
}

#[derive(Clone, Copy)]
struct Fence {
    marker: u8,
    length: usize,
}

fn fence_start(line: &str) -> Option<(Fence, &str)> {
    let indentation = line.len() - line.trim_start().len();
    if indentation > 3 {
        return None;
    }
    let trimmed = line.trim_start();
    let marker @ (b'`' | b'~') = trimmed.bytes().next()? else {
        return None;
    };
    let length = trimmed.bytes().take_while(|byte| *byte == marker).count();
    (length >= 3).then(|| (Fence { marker, length }, trimmed[length..].trim()))
}

fn fence_end(line: &str, fence: Fence) -> bool {
    let trimmed = line.trim_start();
    let run = trimmed
        .bytes()
        .take_while(|byte| *byte == fence.marker)
        .count();
    run >= fence.length && trimmed[run..].trim().is_empty()
}

fn inside_fence(line: &str, fence: &mut Option<Fence>) -> bool {
    if let Some(active) = *fence {
        if fence_end(line, active) {
            *fence = None;
        }
        return true;
    }

    if let Some((opening, _)) = fence_start(line) {
        *fence = Some(opening);
        true
    } else {
        false
    }
}

/// Parsed fence metadata, shared by rendering and both code-reference resolvers.
#[derive(Debug, PartialEq, Eq)]
pub struct CodeFenceInfo<'a> {
    pub language: &'a str,
    pub reference: Option<&'a str>,
    pub ide_url: Option<&'a str>,
}

impl CodeFenceInfo<'_> {
    /// Info string for an inlined reference, retaining its IDE metadata.
    pub fn resolved_info(&self) -> String {
        match self.ide_url {
            Some(url) => format!("{} ide=\"{url}\"", self.language),
            None => self.language.to_owned(),
        }
    }
}

/// Parse `language [code/path] [ide="URL"]`; unrelated plain fence info is unchanged.
/// IDE URLs must use an explicitly supported editor scheme and contain no raw
/// whitespace, controls, quotes, backslashes, or HTML delimiters.
pub fn parse_code_fence_info(info: &str) -> Result<CodeFenceInfo<'_>> {
    let mut tokens = info.split_whitespace();
    let language = tokens.next().unwrap_or("");
    if language.starts_with("ide=") {
        bail!("IDE metadata requires a language before ide=\"URL\"");
    }
    let mut rest: Vec<_> = tokens.collect();
    let reference = rest
        .first()
        .copied()
        .filter(|token| token.starts_with("code/"));
    if reference.is_some() {
        rest.remove(0);
    }
    let has_ide = rest.iter().any(|token| {
        token
            .split(|ch: char| !ch.is_ascii_alphanumeric() && ch != '_')
            .next()
            == Some("ide")
    });
    if !has_ide && reference.is_none() {
        return Ok(CodeFenceInfo {
            language,
            reference,
            ide_url: None,
        });
    }
    let ide_url = match rest.as_slice() {
        [] if !has_ide => None,
        [attribute] => Some(
            attribute
                .strip_prefix("ide=\"")
                .and_then(|value| value.strip_suffix('"'))
                .context("code fence IDE metadata must be exactly ide=\"URL\" (double-quoted)")?,
        ),
        _ => bail!(
            "code fence accepts a language, optional code/path, and one ide=\"URL\" attribute; malformed or duplicate IDE metadata"
        ),
    };
    if let Some(url) = ide_url {
        if language.eq_ignore_ascii_case("mermaid") {
            bail!("Mermaid fences do not support ide metadata");
        }
        let allowed = url.split_once(':').is_some_and(|(scheme, destination)| {
            !destination.is_empty()
                && matches!(
                    scheme.to_ascii_lowercase().as_str(),
                    "zed"
                        | "vscode"
                        | "vscode-insiders"
                        | "idea"
                        | "pycharm"
                        | "clion"
                        | "goland"
                        | "rustrover"
                        | "webstorm"
                        | "phpstorm"
                        | "rider"
                        | "rubymine"
                        | "datagrip"
                        | "jetbrains"
                )
        });
        if !allowed
            || url.chars().any(|ch| {
                ch.is_whitespace()
                    || ch.is_control()
                    || matches!(ch, '\'' | '"' | '<' | '>' | '\\' | '`')
            })
        {
            bail!(
                "invalid ide URL: use a supported editor scheme (e.g. zed: or vscode:) and percent-encode whitespace, controls, quotes, and delimiters"
            );
        }
    }
    Ok(CodeFenceInfo {
        language,
        reference,
        ide_url,
    })
}

pub fn resolve_code_references(source: &str) -> Result<String> {
    resolve_code_references_from(source, Path::new("examples"))
}

fn resolve_code_references_from(source: &str, presentation_root: &Path) -> Result<String> {
    let lines: Vec<&str> = source.split_inclusive('\n').collect();
    let mut output = String::with_capacity(source.len());
    let mut regular_fence = None;
    let mut index = 0;

    while index < lines.len() {
        let line = lines[index];
        if regular_fence.is_some() {
            inside_fence(line, &mut regular_fence);
            output.push_str(line);
            index += 1;
            continue;
        }

        let Some((fence, info)) = fence_start(line) else {
            output.push_str(line);
            index += 1;
            continue;
        };
        let info = parse_code_fence_info(info)?;
        let Some(reference) = info.reference else {
            regular_fence = Some(fence);
            output.push_str(line);
            index += 1;
            continue;
        };

        let indentation = line.len() - line.trim_start().len();
        output.push_str(&line[..indentation]);
        output.extend(std::iter::repeat_n(char::from(fence.marker), fence.length));
        output.push_str(&info.resolved_info());
        output.push('\n');

        index += 1;
        while index < lines.len() && !fence_end(lines[index], fence) {
            if !lines[index].trim().is_empty() {
                bail!("code reference {reference:?} cannot also contain inline code");
            }
            index += 1;
        }
        if index == lines.len() {
            bail!("code reference {reference:?} is missing its closing fence");
        }

        let code = read_code_reference(presentation_root, reference)?;
        if code.lines().any(|line| fence_end(line, fence)) {
            bail!("code reference {reference:?} contains the closing fence marker");
        }
        output.push_str(&code);
        if !code.is_empty() && !code.ends_with('\n') {
            output.push('\n');
        }
        output.push_str(lines[index]);
        index += 1;
    }

    Ok(output)
}

fn read_code_reference(presentation_root: &Path, reference: &str) -> Result<String> {
    let relative = Path::new(reference);
    let mut components = relative.components();
    let inside_code = matches!(
        components.next(),
        Some(Component::Normal(component)) if component == "code"
    ) && components.all(|component| matches!(component, Component::Normal(_)));
    if !inside_code {
        bail!("code references must stay inside the code/ directory");
    }

    let code_root = fs::canonicalize(presentation_root.join("code"))
        .context("could not resolve the presentation code directory")?;
    let path = fs::canonicalize(presentation_root.join(relative))
        .with_context(|| format!("could not resolve code reference {reference:?}"))?;
    if !path.starts_with(&code_root) {
        bail!("code references must stay inside the code/ directory");
    }
    fs::read_to_string(&path)
        .with_context(|| format!("could not read code reference {reference:?} as UTF-8"))
}

/// Return nonempty slide source slices, ignoring separators inside code fences.
pub fn split_slides(source: &str) -> Vec<&str> {
    let mut slides = Vec::new();
    let mut start = 0;
    let mut fence = None;

    for (offset, line) in source.split_inclusive('\n').scan(0, |offset, line| {
        let current = *offset;
        *offset += line.len();
        Some((current, line))
    }) {
        if !inside_fence(line, &mut fence) && line.trim() == "---" {
            if let Some(slide) = nonempty_slide(&source[start..offset]) {
                slides.push(slide);
            }
            start = offset + line.len();
        }
    }

    if let Some(slide) = nonempty_slide(&source[start..]) {
        slides.push(slide);
    }
    slides
}

fn nonempty_slide(source: &str) -> Option<&str> {
    let source = source.trim_matches(['\r', '\n']);
    (!source.trim().is_empty()).then_some(source)
}

const IFRAME_MARKER_PREFIX: &str = "\u{e000}slides-iframe-";
const REVEAL_MARKER_PREFIX: &str = "\u{e000}slides-reveal-";
const REVEAL_START: &str = "\u{e000}slides-reveal-start\u{e001}";
const REVEAL_END: &str = "\u{e000}slides-reveal-end\u{e001}";

#[derive(Debug)]
struct IframeSpec {
    src: String,
    asset_path: String,
    title: String,
}

#[derive(Debug)]
struct ExtractedSlide {
    markdown: String,
    iframes: Vec<IframeSpec>,
    interaction: Option<Interaction>,
    notes: Option<String>,
}

fn parse_slide(source: &str, slide_index: usize) -> Result<Slide> {
    let source = resolve_code_references(source)?;
    if source.contains(IFRAME_MARKER_PREFIX) {
        bail!("slide content contains a reserved iframe marker");
    }
    if source.contains(REVEAL_MARKER_PREFIX) {
        bail!("slide content contains a reserved reveal marker");
    }
    let extracted = extract_directives(&source)?;
    let mut mermaid_diagrams = Vec::new();
    let (mut html, reveal_count) =
        render_markdown_with_reveals(&extracted.markdown, &mut mermaid_diagrams)?;
    for (iframe_index, iframe) in extracted.iframes.iter().enumerate() {
        let marker = format!("<p>{}</p>\n", iframe_marker(iframe_index));
        if !html.contains(&marker) {
            bail!("could not place iframe in rendered slide");
        }
        html = html.replacen(
            &marker,
            &render_iframe(iframe, slide_index, iframe_index),
            1,
        );
    }
    let iframe_assets = extracted
        .iframes
        .into_iter()
        .map(|iframe| iframe.asset_path)
        .collect();
    Ok(Slide {
        html,
        reveal_count,
        interaction: extracted.interaction,
        notes: extracted
            .notes
            .map(|notes| render_markdown(&notes, &mut mermaid_diagrams))
            .transpose()?,
        iframe_assets,
        mermaid_diagrams,
    })
}

fn extract_directives(source: &str) -> Result<ExtractedSlide> {
    let lines: Vec<&str> = source.lines().collect();
    // Protect directive examples using both Markdown code ranges (including
    // nested fences) and legacy fence boundaries hidden by HTML blocks.
    let code_lines = markdown_code_lines(source);
    let mut output = Vec::new();
    let mut iframes = Vec::new();
    let mut interaction = None;
    let mut notes = None;
    let mut index = 0;

    while index < lines.len() {
        if code_lines[index] {
            output.push(lines[index].to_owned());
            index += 1;
            continue;
        }
        let Some(line) = directive_line(lines[index]) else {
            output.push(lines[index].to_owned());
            index += 1;
            continue;
        };
        let interaction_name = interaction_kind(line);
        let directive = directive_name(line);
        let is_notes = directive == Some("notes");
        let is_iframe = directive == Some("iframe");
        let is_reveal = directive == Some("reveal");
        if interaction_name.is_none() && !is_notes && !is_iframe && !is_reveal {
            output.push(lines[index].to_owned());
            index += 1;
            continue;
        }

        if is_reveal && line != ":::reveal" {
            bail!("a reveal block does not accept arguments; use :::reveal on its own line");
        }

        let inline_header = is_iframe
            .then_some(line)
            .and_then(self_closing_directive_header);
        let header = inline_header.unwrap_or(line).to_owned();
        let mut body = Vec::new();
        index += 1;
        if inline_header.is_none() {
            while index < lines.len() {
                if !code_lines[index] {
                    let body_line = directive_line(lines[index]);
                    if body_line == Some(":::") {
                        break;
                    }
                    let body_directive = body_line.and_then(directive_name);
                    if body_directive == Some("reveal") {
                        if is_notes {
                            bail!(
                                "reveal directives are not allowed in presenter notes; put reveal examples in a fenced code block"
                            );
                        }
                        bail!("reveal blocks cannot be nested inside another directive block");
                    }
                    if is_reveal && body_directive.is_some() {
                        bail!(
                            "directives cannot be nested in a reveal block; move notes, iframes and interactions outside :::reveal"
                        );
                    }
                }
                body.push(lines[index]);
                index += 1;
            }
            if index == lines.len() {
                let name = if is_notes {
                    "presenter notes"
                } else if is_iframe {
                    "iframe"
                } else if is_reveal {
                    "reveal"
                } else {
                    "interactive"
                };
                bail!("{name} block is missing its closing :::");
            }
            index += 1;
        }

        if is_reveal {
            // Separate marker paragraphs keep adjacent lists/blocks distinct while
            // parsing the whole slide once, preserving reference definitions.
            output.push(String::new());
            output.push(REVEAL_START.to_owned());
            output.push(String::new());
            output.extend(body.into_iter().map(str::to_owned));
            output.push(String::new());
            output.push(REVEAL_END.to_owned());
            output.push(String::new());
            continue;
        }

        if is_notes {
            if header != ":::notes" {
                bail!("a presenter notes block does not accept arguments");
            }
            if notes.is_some() {
                bail!("only one presenter notes block is allowed per slide");
            }
            notes = Some(body.join("\n").trim().to_owned());
            continue;
        }

        if is_iframe {
            output.push(String::new());
            output.push(iframe_marker(iframes.len()));
            output.push(String::new());
            iframes.push(parse_iframe(&header, &body)?);
            continue;
        }

        if interaction.is_some() {
            bail!("only one interactive block is allowed per slide");
        }
        interaction = Some(match interaction_name {
            Some("poll") => parse_poll(&header, &body)?,
            Some("wordcloud") => parse_word_cloud(&header, &body)?,
            Some("quiz") => parse_quiz(&header, &body)?,
            Some("ordering") => parse_ordering(&header, &body)?,
            Some(_) | None => unreachable!(),
        });
    }

    Ok(ExtractedSlide {
        markdown: output.join("\n"),
        iframes,
        interaction,
        notes,
    })
}

fn markdown_code_lines(source: &str) -> Vec<bool> {
    let mut ranges = Parser::new(source)
        .into_offset_iter()
        .filter_map(|(event, range)| {
            matches!(event, Event::Start(Tag::CodeBlock(_))).then_some(range)
        })
        .peekable();
    let mut offset = 0;
    let mut fence = None;
    source
        .split_inclusive('\n')
        .map(|line| {
            let end = offset + line.len();
            while ranges.peek().is_some_and(|range| range.end <= offset) {
                ranges.next();
            }
            let is_code = ranges.peek().is_some_and(|range| range.start < end);
            let starts_code = ranges
                .peek()
                .is_some_and(|range| (offset..end).contains(&range.start));
            // Preserve legacy fences even when CommonMark treats them as HTML.
            // Do not mistake a nested code block's closing fence for an opener.
            let in_fence =
                (fence.is_some() || !is_code || starts_code) && inside_fence(line, &mut fence);
            offset = end;
            is_code || in_fence
        })
        .collect()
}

fn iframe_marker(index: usize) -> String {
    format!("{IFRAME_MARKER_PREFIX}{index}\u{e001}")
}

fn directive_line(line: &str) -> Option<&str> {
    let trimmed = line.trim_start();
    let indentation = &line[..line.len() - trimmed.len()];
    (!indentation.contains('\t') && indentation.len() <= 3).then(|| trimmed.trim_end())
}

fn directive_name(line: &str) -> Option<&str> {
    line.strip_prefix(":::")?.split_whitespace().next()
}

fn self_closing_directive_header(line: &str) -> Option<&str> {
    line.strip_suffix(" :::")
}

fn interaction_kind(line: &str) -> Option<&'static str> {
    match directive_name(line)? {
        "poll" => Some("poll"),
        "wordcloud" => Some("wordcloud"),
        "quiz" => Some("quiz"),
        "ordering" => Some("ordering"),
        _ => None,
    }
}

fn parse_iframe(header: &str, body: &[&str]) -> Result<IframeSpec> {
    let arguments = parse_arguments(
        &std::iter::once(header)
            .chain(body.iter().copied())
            .collect::<Vec<_>>()
            .join(" "),
        &["src", "title"],
        &[],
    )?;

    let src = arguments
        .attribute("src")
        .context("an iframe requires a src attribute")?
        .trim();
    let title = arguments
        .attribute("title")
        .context("an iframe requires a title attribute")?
        .trim();
    if title.is_empty() {
        bail!("an iframe title cannot be empty");
    }
    if title.chars().count() > 200 || title.chars().any(char::is_control) {
        bail!("an iframe title must be at most 200 characters and contain no control characters");
    }
    if src.chars().any(char::is_control) || src.contains(['\\', '%', ':']) {
        bail!("an iframe src contains unsupported characters");
    }

    let path_end = src.find(['?', '#']).unwrap_or(src.len());
    let path = &src[..path_end];
    let relative = path
        .strip_prefix("/assets/")
        .context("an iframe src must start with /assets/")?;
    let components = relative.split('/').collect::<Vec<_>>();
    if components.len() < 3
        || components[0] != "embeds"
        || components
            .iter()
            .any(|component| component.is_empty() || *component == "." || *component == "..")
    {
        bail!("an iframe src must point inside /assets/embeds/<bundle>/");
    }
    let extension = Path::new(relative)
        .extension()
        .and_then(|value| value.to_str())
        .unwrap_or_default();
    if !extension.eq_ignore_ascii_case("html") && !extension.eq_ignore_ascii_case("htm") {
        bail!("an iframe src must point to an HTML file");
    }

    Ok(IframeSpec {
        src: src.to_owned(),
        asset_path: relative.to_owned(),
        title: title.to_owned(),
    })
}

fn render_iframe(iframe: &IframeSpec, slide_index: usize, iframe_index: usize) -> String {
    format!(
        "<figure class=\"iframe-embed\"><iframe id=\"slide-iframe-{}-{}\" class=\"slide-iframe\" src=\"{}\" title=\"{}\" sandbox=\"allow-scripts\" referrerpolicy=\"no-referrer\"></iframe></figure>",
        slide_index + 1,
        iframe_index + 1,
        html_escape::encode_double_quoted_attribute(&iframe.src),
        html_escape::encode_double_quoted_attribute(&iframe.title),
    )
}

fn parse_poll(header: &str, body: &[&str]) -> Result<Interaction> {
    let arguments = parse_arguments(header, &["question", "orientation"], &["multiple"])?;
    let question = arguments
        .attribute("question")
        .filter(|question| !question.trim().is_empty())
        .map(str::to_owned);
    let options = list_items(body);
    if options.len() < 2 {
        bail!("a poll needs at least two options");
    }
    let orientation = match arguments.attribute("orientation") {
        Some("vertical") => ChartOrientation::Vertical,
        Some("horizontal") | None => ChartOrientation::Horizontal,
        Some(value) => bail!("unsupported chart orientation {value:?}"),
    };
    Ok(Interaction::Poll {
        question,
        options,
        multiple: arguments.flag("multiple"),
        orientation,
    })
}

fn parse_word_cloud(header: &str, body: &[&str]) -> Result<Interaction> {
    let arguments = parse_arguments(header, &["prompt", "max"], &[])?;
    if body.iter().any(|line| !line.trim().is_empty()) {
        bail!("a word-cloud block cannot contain body content");
    }
    let prompt = arguments
        .attribute("prompt")
        .unwrap_or("What comes to mind?")
        .to_owned();
    let max_length = arguments
        .attribute("max")
        .map(str::parse::<usize>)
        .transpose()
        .context("word-cloud max must be a number")?
        .unwrap_or(80)
        .clamp(1, 240);
    Ok(Interaction::WordCloud { prompt, max_length })
}

fn parse_quiz(header: &str, body: &[&str]) -> Result<Interaction> {
    let arguments = parse_arguments(header, &["question"], &[])?;
    let question = arguments
        .attribute("question")
        .unwrap_or("Choose the correct answer")
        .to_owned();
    let mut options = Vec::new();
    for line in body {
        let (correct, label) = if let Some(label) = line.strip_prefix("- [x]") {
            (true, label.trim())
        } else if let Some(label) = line.strip_prefix("- [X]") {
            (true, label.trim())
        } else if let Some(label) = line.strip_prefix("- [ ]") {
            (false, label.trim())
        } else {
            continue;
        };
        if !label.is_empty() {
            options.push(QuizOption {
                label: label.to_owned(),
                correct,
            });
        }
    }
    if options.len() < 2 {
        bail!("a quiz needs at least two checkbox-style options");
    }
    if !options.iter().any(|option| option.correct) {
        bail!("a quiz needs at least one correct option marked with [x]");
    }
    Ok(Interaction::Quiz { question, options })
}

fn parse_ordering(header: &str, body: &[&str]) -> Result<Interaction> {
    let arguments = parse_arguments(header, &["prompt"], &[])?;
    let prompt = arguments
        .attribute("prompt")
        .unwrap_or("Put these items in order")
        .to_owned();
    let options = list_items(body);
    if options.len() < 2 {
        bail!("an ordering interaction needs at least two items");
    }
    Ok(Interaction::Ordering { prompt, options })
}

fn list_items(lines: &[&str]) -> Vec<String> {
    lines
        .iter()
        .filter_map(|line| line.strip_prefix("- "))
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_owned)
        .collect()
}

#[derive(Debug, Default)]
struct DirectiveArguments {
    attributes: Vec<(String, String)>,
    flags: Vec<String>,
}

impl DirectiveArguments {
    fn attribute(&self, key: &str) -> Option<&str> {
        self.attributes
            .iter()
            .find_map(|(name, value)| (name == key).then_some(value.as_str()))
    }

    fn flag(&self, name: &str) -> bool {
        self.flags.iter().any(|flag| flag == name)
    }
}

fn parse_arguments(
    header: &str,
    allowed_attributes: &[&str],
    allowed_flags: &[&str],
) -> Result<DirectiveArguments> {
    let directive = header
        .strip_prefix(":::")
        .context("directive must start with :::")?;
    let name_end = directive
        .find(char::is_whitespace)
        .unwrap_or(directive.len());
    let mut input = &directive[name_end..];
    let mut arguments = DirectiveArguments::default();

    while !input.trim_start().is_empty() {
        input = input.trim_start();
        let key_end = input
            .find(|character: char| character.is_whitespace() || character == '=')
            .unwrap_or(input.len());
        if key_end == 0 {
            bail!("malformed directive argument near {input:?}");
        }
        let key = &input[..key_end];
        input = &input[key_end..];

        if let Some(value_input) = input.strip_prefix("=\"") {
            if !allowed_attributes.contains(&key) {
                bail!("unsupported directive attribute {key:?}");
            }
            if arguments
                .attributes
                .iter()
                .any(|(existing, _)| existing == key)
            {
                bail!("duplicate directive attribute {key:?}");
            }
            let value_end = value_input.find('"').with_context(|| {
                format!("directive attribute {key:?} is missing a closing quote")
            })?;
            let after = &value_input[value_end + 1..];
            if after
                .chars()
                .next()
                .is_some_and(|character| !character.is_whitespace())
            {
                bail!("directive attribute {key:?} must be followed by whitespace");
            }
            arguments
                .attributes
                .push((key.to_owned(), value_input[..value_end].to_owned()));
            input = after;
        } else if input.starts_with('=') {
            bail!("directive attribute {key:?} must use a quoted value");
        } else {
            if !allowed_flags.contains(&key) {
                bail!("unsupported directive flag {key:?}");
            }
            if arguments.flags.iter().any(|existing| existing == key) {
                bail!("duplicate directive flag {key:?}");
            }
            arguments.flags.push(key.to_owned());
        }
    }

    Ok(arguments)
}

fn render_markdown(source: &str, mermaid_diagrams: &mut Vec<String>) -> Result<String> {
    render_markdown_with_reveals(source, mermaid_diagrams).map(|(html, _)| html)
}

fn render_markdown_with_reveals(
    source: &str,
    mermaid_diagrams: &mut Vec<String>,
) -> Result<(String, usize)> {
    let mut options = Options::empty();
    options.insert(Options::ENABLE_STRIKETHROUGH);
    options.insert(Options::ENABLE_TABLES);
    options.insert(Options::ENABLE_TASKLISTS);

    let mut parser = Parser::new_ext(source, options).into_offset_iter();
    let mut rendered_events = Vec::new();
    let mut code_block: Option<(String, Option<String>, String)> = None;
    let mut depth = 0;
    let mut reveal_start = None;
    let mut reveal_count = 0;
    let mut marker_count = 0;

    while let Some((event, range)) = parser.next() {
        // Match source bytes, not decoded Text: entity-encoded marker lookalikes
        // are ordinary user content, never generated reveal boundaries.
        if matches!(event, Event::Start(Tag::Paragraph))
            && matches!(source[range.clone()].trim(), REVEAL_START | REVEAL_END)
        {
            let opening = source[range].trim() == REVEAL_START;
            marker_count += 1;
            parser.next();
            if depth != 0 || !matches!(parser.next(), Some((Event::End(TagEnd::Paragraph), _))) {
                bail!("reveal blocks must be top-level blocks, outside lists and block quotes");
            }
            if opening {
                if reveal_start.replace(reveal_count).is_some() {
                    bail!("reveal blocks cannot be nested");
                }
            } else {
                let Some(start) = reveal_start.take() else {
                    bail!("reveal block has no opening :::reveal");
                };
                if start == reveal_count {
                    bail!("a reveal block needs at least one paragraph or list item");
                }
            }
            continue;
        }

        let reveal_tag = if reveal_start.is_some() {
            match &event {
                Event::Start(Tag::Paragraph) if depth == 0 => Some("p"),
                Event::Start(Tag::Item) if depth == 1 => Some("li"),
                Event::Start(Tag::List(_)) if depth == 0 => None,
                _ if depth == 0 => {
                    bail!(
                        "reveal blocks support only top-level paragraphs and lists; move headings, code blocks, tables and other content outside :::reveal"
                    );
                }
                _ => None,
            }
        } else {
            None
        };
        match &event {
            Event::Start(_) => depth += 1,
            Event::End(_) => depth -= 1,
            _ => {}
        }
        if let Some(tag) = reveal_tag {
            reveal_count += 1;
            rendered_events.push(Event::Html(CowStr::Boxed(
                format!("<{tag} data-reveal-step=\"{reveal_count}\">").into_boxed_str(),
            )));
            continue;
        }

        match event {
            Event::Start(Tag::CodeBlock(kind)) => {
                let (language, ide_url) = match kind {
                    CodeBlockKind::Fenced(value) => {
                        let info = parse_code_fence_info(&value)?;
                        (info.language.to_owned(), info.ide_url.map(str::to_owned))
                    }
                    CodeBlockKind::Indented => (String::new(), None),
                };
                code_block = Some((language, ide_url, String::new()));
            }
            Event::End(TagEnd::CodeBlock) => {
                if let Some((language, ide_url, code)) = code_block.take() {
                    rendered_events.push(Event::Html(CowStr::Boxed(
                        render_code_block(&language, &code, ide_url.as_deref()).into_boxed_str(),
                    )));
                    if language.eq_ignore_ascii_case("mermaid") {
                        mermaid_diagrams.push(code);
                    }
                }
            }
            Event::Text(text) if code_block.is_some() => {
                if let Some((_, _, code)) = code_block.as_mut() {
                    code.push_str(&text);
                }
            }
            Event::SoftBreak | Event::HardBreak if code_block.is_some() => {
                if let Some((_, _, code)) = code_block.as_mut() {
                    code.push('\n');
                }
            }
            Event::Html(raw) | Event::InlineHtml(raw) => {
                rendered_events.push(Event::Text(raw));
            }
            Event::Start(Tag::Link {
                dest_url, title, ..
            }) => {
                let destination = safe_link_destination(dest_url);
                let title = if title.is_empty() {
                    String::new()
                } else {
                    format!(
                        " title=\"{}\"",
                        html_escape::encode_double_quoted_attribute(&title)
                    )
                };
                let external = if is_external_destination(&destination) {
                    " target=\"_blank\" rel=\"noopener noreferrer\""
                } else {
                    ""
                };
                rendered_events.push(Event::Html(CowStr::Boxed(
                    format!(
                        "<a href=\"{}\"{title}{external}>",
                        html_escape::encode_double_quoted_attribute(&destination)
                    )
                    .into_boxed_str(),
                )));
            }
            Event::End(TagEnd::Link) => {
                rendered_events.push(Event::Html(CowStr::Borrowed("</a>")));
            }
            Event::Start(Tag::Image {
                link_type,
                dest_url,
                title,
                id,
            }) => rendered_events.push(Event::Start(Tag::Image {
                link_type,
                dest_url: safe_destination(dest_url),
                title,
                id,
            })),
            other if code_block.is_none() => rendered_events.push(other),
            _ => {}
        }
    }

    if reveal_start.is_some() {
        bail!("could not place the closing reveal marker; end all Markdown blocks before :::");
    }
    if marker_count != source.matches(REVEAL_MARKER_PREFIX).count() {
        bail!(
            "reveal blocks must be top-level blocks; close surrounding Markdown or HTML blocks before :::reveal"
        );
    }
    let mut output = String::new();
    html::push_html(&mut output, rendered_events.into_iter());
    Ok((output, reveal_count))
}

fn is_external_destination(destination: &str) -> bool {
    let destination = destination.trim().to_ascii_lowercase();
    destination.starts_with("http://") || destination.starts_with("https://")
}

fn safe_link_destination<'a>(destination: CowStr<'a>) -> CowStr<'a> {
    if destination
        .trim()
        .get(..4)
        .is_some_and(|scheme| scheme.eq_ignore_ascii_case("zed:"))
    {
        destination
    } else {
        safe_destination(destination)
    }
}

fn safe_destination<'a>(destination: CowStr<'a>) -> CowStr<'a> {
    let value = destination.trim().to_ascii_lowercase();
    let relative = value.starts_with('/')
        || value.starts_with('#')
        || value.starts_with("./")
        || value.starts_with("../")
        || !value.contains(':');
    if relative
        || value.starts_with("http://")
        || value.starts_with("https://")
        || value.starts_with("mailto:")
    {
        destination
    } else {
        CowStr::Borrowed("#")
    }
}

fn render_code_block(language: &str, code: &str, ide_url: Option<&str>) -> String {
    if language.trim().eq_ignore_ascii_case("mermaid") {
        return format!(
            "<figure class=\"mermaid-diagram\" data-mermaid-diagram><pre class=\"mermaid-source\" data-mermaid-source><code>{}</code></pre><div class=\"mermaid-output\" data-mermaid-output hidden></div><p class=\"mermaid-error\" data-mermaid-error role=\"status\" hidden>Could not render this diagram. Check the Mermaid syntax.</p></figure>",
            html_escape::encode_text(code)
        );
    }

    highlight_code_with_ide(language, code, ide_url)
}

/// Render a syntax-highlighted HTML code block using the bundled theme.
pub fn highlight_code(language: &str, code: &str) -> String {
    highlight_code_with_ide(language, code, None)
}

fn highlight_code_with_ide(language: &str, code: &str, ide_url: Option<&str>) -> String {
    static SYNTAX_SET: OnceLock<SyntaxSet> = OnceLock::new();
    static THEME: OnceLock<Theme> = OnceLock::new();

    let syntaxes = SYNTAX_SET.get_or_init(SyntaxSet::load_defaults_newlines);
    let theme = THEME.get_or_init(|| {
        let mut reader = Cursor::new(include_bytes!("../assets/catppuccin-mocha.tmTheme"));
        ThemeSet::load_from_reader(&mut reader).expect("embedded Catppuccin Mocha theme")
    });
    let syntax = syntaxes
        .find_syntax_by_token(language)
        .unwrap_or_else(|| syntaxes.find_syntax_plain_text());

    let highlighted = highlighted_html_for_string(code, syntaxes, syntax, theme)
        .unwrap_or_else(|_| format!("<pre><code>{}</code></pre>", html_escape::encode_text(code)));
    let ide_attribute = ide_url
        .map(|url| {
            format!(
                " data-code-ide-url=\"{}\"",
                html_escape::encode_double_quoted_attribute(url)
            )
        })
        .unwrap_or_default();
    if matches!(language.trim().to_ascii_lowercase().as_str(), "rust" | "rs") {
        format!("<div class=\"rust-code\" data-rust-code{ide_attribute}>{highlighted}</div>")
    } else if ide_url.is_some() {
        format!("<div class=\"rust-code\"{ide_attribute}>{highlighted}</div>")
    } else {
        highlighted
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reveals_paragraphs_and_top_level_items_in_order() {
        let deck = parse_deck(
            "# Always visible\n\nBefore.\n\n:::reveal\nFirst **paragraph**.\nStill the same paragraph.\n\nSecond paragraph.\n\n- First bullet\n  - Nested bullet\n    1. Nested ordered item\n- Second bullet\n\n3. Third step in a different list\n4. Another ordered item\n:::\n\nAfter.",
        )
        .unwrap();
        let slide = &deck.slides[0];
        assert_eq!(slide.reveal_count, 6);
        assert!(slide.html.contains("<h1>Always visible</h1>"));
        assert!(slide.html.contains("<p>Before.</p>"));
        assert!(slide.html.contains("<p>After.</p>"));
        assert!(slide.html.contains("<p data-reveal-step=\"1\">First <strong>paragraph</strong>.\nStill the same paragraph.</p>"));
        assert!(
            slide
                .html
                .contains("<p data-reveal-step=\"2\">Second paragraph.</p>")
        );
        assert!(
            slide
                .html
                .contains("<li data-reveal-step=\"3\">First bullet")
        );
        assert!(slide.html.contains("<li>Nested bullet"));
        assert!(slide.html.contains("<li>Nested ordered item</li>"));
        assert!(
            slide
                .html
                .contains("<li data-reveal-step=\"4\">Second bullet")
        );
        assert!(slide.html.contains("<ol start=\"3\">"));
        assert!(slide.html.contains("<li data-reveal-step=\"5\">Third step"));
        assert!(
            slide
                .html
                .contains("<li data-reveal-step=\"6\">Another ordered item")
        );
        assert!(!slide.html.contains(REVEAL_MARKER_PREFIX));
        assert!(!slide.html.contains(":::"));
        assert!(!slide.html.contains("data-reveal-pending"));
        assert!(!slide.html.contains("aria-hidden"));
        assert!(!slide.html.contains("inert"));
    }

    #[test]
    fn loose_list_items_reveal_all_their_content_together() {
        let deck = parse_deck(
            ":::reveal\n- First paragraph\n\n  Second paragraph with [a link](https://example.com).\n\n  - Nested item\n\n    More nested content.\n\n- [x] Second item\n:::",
        )
        .unwrap();
        let slide = &deck.slides[0];
        assert_eq!(slide.reveal_count, 2);
        assert!(
            slide
                .html
                .replace('\n', "")
                .contains("<li data-reveal-step=\"1\"><p>First paragraph</p>")
        );
        assert!(slide.html.contains("<p>Second paragraph with <a"));
        assert!(
            slide
                .html
                .replace('\n', "")
                .contains("<li><p>Nested item</p>")
        );
        assert!(slide.html.contains("type=\"checkbox\""));
        assert_eq!(
            slide.html_at_step(0).matches("data-reveal-pending").count(),
            2
        );
        assert_eq!(
            slide.html_at_step(1).matches("data-reveal-pending").count(),
            1
        );
    }

    #[test]
    fn reveal_steps_span_blocks_but_restart_per_slide() {
        let deck = parse_deck(
            "- Before\n\n:::reveal\n- One\n- Two\n:::\n:::reveal\n- Three\n:::\n\n- After\n\n---\n\n:::reveal\nNext slide\n:::",
        )
        .unwrap();
        let first = &deck.slides[0];
        assert_eq!(first.reveal_count, 3);
        assert_eq!(first.html.matches("<ul>").count(), 4);
        assert!(first.html.contains("<li>Before</li>"));
        assert!(first.html.contains("<li>After</li>"));
        assert!(first.html.contains("<li data-reveal-step=\"3\">Three</li>"));
        assert_eq!(deck.slides[1].reveal_count, 1);
        assert!(
            deck.slides[1]
                .html
                .contains("<p data-reveal-step=\"1\">Next slide</p>")
        );
    }

    #[test]
    fn renders_pending_steps_without_hiding_or_mutating_base_html() {
        let deck = parse_deck("Visible\n\n:::reveal\nOne\n\n- Two\n:::").unwrap();
        let slide = &deck.slides[0];
        let original = slide.html.clone();
        for step in [0, 1, 2, 3, usize::MAX] {
            let html = slide.html_at_step(step);
            assert_eq!(
                html.matches("data-reveal-pending").count(),
                2usize.saturating_sub(step)
            );
            assert_eq!(
                html.matches("aria-hidden=\"true\"").count(),
                2usize.saturating_sub(step)
            );
            assert_eq!(html.matches(" inert").count(), 2usize.saturating_sub(step));
            assert!(!html.contains(" hidden"));
            assert!(!html.contains("style="));
            assert!(html.contains("<p>Visible</p>"));
            assert!(html.contains("One</p>"));
            assert!(html.contains("Two</li>"));
            if step >= 2 {
                assert!(matches!(html, Cow::Borrowed(_)));
                assert_eq!(html, original);
            } else {
                assert!(matches!(html, Cow::Owned(_)));
            }
        }
        assert!(slide.html_at_step(0).contains(
            "<p data-reveal-step=\"1\" data-reveal-pending aria-hidden=\"true\" inert>One</p>"
        ));
        assert!(slide.html_at_step(1).contains(
            "<li data-reveal-step=\"2\" data-reveal-pending aria-hidden=\"true\" inert>Two</li>"
        ));
        assert_eq!(slide.html, original);
        assert_eq!(slide.html_at_step(0), slide.html_at_step(0));
    }

    #[test]
    fn reveal_blocks_preserve_whole_slide_reference_links() {
        let deck = parse_deck(
            "[Outside][inside]\n\n:::reveal\n[First][later]\n\n[inside]: https://inside.example\n:::\n\n:::reveal\n- [Second][inside]\n:::\n\n[later]: https://later.example",
        )
        .unwrap();
        let slide = &deck.slides[0];
        assert_eq!(slide.reveal_count, 2);
        assert_eq!(
            slide
                .html
                .matches("href=\"https://inside.example\"")
                .count(),
            2
        );
        assert_eq!(
            slide.html.matches("href=\"https://later.example\"").count(),
            1
        );
    }

    #[test]
    fn rejects_malformed_or_unsupported_reveal_blocks() {
        for (source, message) in [
            (":::reveal\nUnclosed", "missing its closing"),
            (":::reveal\n```text\n:::fold\n:::", "missing its closing"),
            (
                ":::reveal mode=\"all\"\nText\n:::",
                "does not accept arguments",
            ),
            (":::reveal :::", "does not accept arguments"),
            (":::reveal\n:::", "at least one paragraph or list item"),
            (
                ":::reveal\n \n\t\n:::",
                "at least one paragraph or list item",
            ),
            (
                ":::reveal\n[ref]: https://example.com\n:::",
                "at least one paragraph or list item",
            ),
            (
                ":::reveal\nFirst\n:::reveal\nSecond\n:::\n:::",
                "cannot be nested",
            ),
            (
                ":::reveal\n# Heading\n:::",
                "only top-level paragraphs and lists",
            ),
            (
                ":::reveal\n```text\ncode\n```\n:::",
                "only top-level paragraphs and lists",
            ),
            (
                ":::reveal\n    indented code\n:::",
                "only top-level paragraphs and lists",
            ),
            (
                ":::reveal\n> Quote\n:::",
                "only top-level paragraphs and lists",
            ),
            (
                ":::reveal\n| A | B |\n| - | - |\n| C | D |\n:::",
                "only top-level paragraphs and lists",
            ),
            (":::reveal\n***\n:::", "only top-level paragraphs and lists"),
            (
                ":::reveal\n<div>Raw block</div>\n:::",
                "only top-level paragraphs and lists",
            ),
            (
                ":::reveal\n:::iframe src=\"/assets/embeds/demo.html\" title=\"Demo\" :::\n:::",
                "cannot be nested",
            ),
            (
                ":::reveal\n:::poll\n- Yes\n- No\n:::\n:::",
                "cannot be nested",
            ),
            (":::reveal\n:::notes\nNotes\n:::\n:::", "cannot be nested"),
            (
                ":::poll\n:::reveal\n- One\n- Two\n:::\n:::",
                "cannot be nested",
            ),
        ] {
            let error = format!("{:#}", parse_deck(source).unwrap_err());
            assert!(error.contains("slide 1"), "{source}: {error}");
            assert!(error.contains(message), "{source}: {error}");
        }
    }

    #[test]
    fn reveal_directive_examples_in_code_are_not_interpreted() {
        for source in [
            "```markdown\n:::reveal\nExample\n:::\n```",
            "~~~markdown\n:::reveal arguments\n:::reveal\n:::notes\n:::\n~~~",
            "````markdown\n```\n:::reveal\nExample\n:::\n```\n````",
            "    :::reveal\n    Example\n    :::",
            "- ```markdown\n  :::reveal\n  Example\n  :::\n  ```",
            "> ```markdown\n> :::reveal\n> Example\n> :::\n> ```",
        ] {
            let slide = parse_deck(source).unwrap().slides.remove(0);
            assert_eq!(slide.reveal_count, 0, "{source}");
            assert!(!slide.html.contains("data-reveal-step"), "{source}");
            assert!(matches!(slide.html_at_step(0), Cow::Borrowed(_)));
        }
    }

    #[test]
    fn accepts_crlf_and_directive_indentation_and_exact_names() {
        let deck = parse_deck("  :::reveal  \r\nFirst\r\n\r\nSecond\r\n   :::\r\n").unwrap();
        assert_eq!(deck.slides[0].reveal_count, 2);
        let deck = parse_deck(":::revealing\nOrdinary text\n:::").unwrap();
        assert_eq!(deck.slides[0].reveal_count, 0);
        assert!(deck.slides[0].html.contains(":::revealing"));
    }

    #[test]
    fn presenter_notes_are_never_numbered_or_hidden() {
        let deck = parse_deck(
            ":::reveal\nBody\n:::\n\n:::notes\nFirst note\n\n- Second note\n\n```markdown\n:::reveal\nExample\n:::\n```\n:::\n\n:::reveal\nMore body\n:::",
        )
        .unwrap();
        let slide = &deck.slides[0];
        assert_eq!(slide.reveal_count, 2);
        let notes = slide.notes.as_deref().unwrap();
        assert!(notes.contains("<p>First note</p>"));
        assert!(!notes.contains("data-reveal-step"));
        assert!(!notes.contains("data-reveal-pending"));
        assert!(!slide.html_at_step(0).contains("First note"));
        for source in [
            ":::notes\n:::reveal\nNote\n:::\n:::",
            ":::notes\n:::reveal invalid\nNote\n:::\n:::",
        ] {
            let error = format!("{:#}", parse_deck(source).unwrap_err());
            assert!(error.contains("not allowed in presenter notes"), "{error}");
        }
    }

    #[test]
    fn reveals_coexist_with_iframes_interactions_and_exact_mermaid_collection() {
        let deck = parse_deck(
            "```mermaid\nflowchart LR\nA --> B\n```\n\n:::reveal\n- Diagram in an item\n\n  ```mermaid\n  flowchart TD\n  C --> D\n  ```\n\n  ```markdown\n  :::reveal\n  Literal example\n  :::\n  ```\n:::\n\n:::iframe src=\"/assets/embeds/demo/index.html\" title=\"Demo\" :::\n\n:::poll\n- Yes\n- No\n:::\n\n:::notes\n```mermaid\npie\n\"Yes\": 1\n```\n:::",
        )
        .unwrap();
        let slide = &deck.slides[0];
        assert_eq!(slide.reveal_count, 1);
        assert_eq!(
            slide.mermaid_diagrams,
            [
                "flowchart LR\nA --> B\n",
                "flowchart TD\nC --> D\n",
                "pie\n\"Yes\": 1\n"
            ]
        );
        assert_eq!(slide.html.matches("data-mermaid-diagram").count(), 2);
        assert_eq!(
            slide
                .notes
                .as_ref()
                .unwrap()
                .matches("data-mermaid-diagram")
                .count(),
            1
        );
        assert_eq!(slide.iframe_assets, ["embeds/demo/index.html"]);
        assert!(slide.html.contains("sandbox=\"allow-scripts\""));
        assert!(matches!(slide.interaction, Some(Interaction::Poll { .. })));
        assert_eq!(
            slide.html_at_step(0).matches("data-reveal-pending").count(),
            1
        );
    }

    #[test]
    fn only_generated_reveal_elements_can_be_marked_pending() {
        let deck = parse_deck(
            "<p data-reveal-step=\"999\">Raw HTML</p>\n\n:::reveal\nText <span data-reveal-step=\"999\">inline</span>, `<li data-reveal-step=\"999\">`, and [unsafe](javascript:alert).\n:::\n\n```html\n<p data-reveal-step=\"999\">Code</p>\n```",
        )
        .unwrap();
        let slide = &deck.slides[0];
        assert_eq!(slide.reveal_count, 1);
        let pending = slide.html_at_step(0);
        assert_eq!(pending.matches("data-reveal-pending").count(), 1);
        assert!(!pending.contains("<p data-reveal-step=\"999\""));
        assert!(!pending.contains("<li data-reveal-step=\"999\""));
        assert!(!pending.contains("<span data-reveal-step"));
        assert!(pending.contains("href=\"#\""));
        assert_eq!(
            pending.replace(" data-reveal-pending aria-hidden=\"true\" inert", ""),
            slide.html
        );
        let error = parse_deck(&format!(":::reveal\n{REVEAL_START}\n:::")).unwrap_err();
        assert!(format!("{error:#}").contains("reserved reveal marker"));
    }

    #[test]
    fn encoded_internal_markers_are_text_not_reveal_boundaries() {
        let encoded =
            "&#xE000;slides-reveal-start&#xE001;\n\nText\n\n&#xE000;slides-reveal-end&#xE001;";
        let deck = parse_deck(encoded).unwrap();
        assert_eq!(deck.slides[0].reveal_count, 0);
        assert!(!deck.slides[0].html.contains("data-reveal-step"));
        let deck = parse_deck(&format!(":::reveal\n{encoded}\n:::")).unwrap();
        assert_eq!(deck.slides[0].reveal_count, 3);
        assert_eq!(
            deck.slides[0]
                .html_at_step(0)
                .matches("data-reveal-pending")
                .count(),
            3
        );
    }

    #[test]
    fn rejects_reveal_boundaries_swallowed_by_surrounding_html() {
        let error =
            parse_deck("<script>\n\n:::reveal\nNot a Markdown paragraph\n:::\n").unwrap_err();
        assert!(format!("{error:#}").contains("reveal blocks must be top-level"));
    }

    #[test]
    fn ordinary_decks_keep_their_rendering_and_have_no_reveals() {
        for source in [
            "# Title\n\nParagraph\n\n- One\n- Two\n\n3. Three\n4. Four",
            include_str!("../examples/kitchen-sink.md"),
            include_str!("../examples/intro-to-rust.md"),
        ] {
            let deck = parse_deck(source).unwrap();
            for slide in &deck.slides {
                assert_eq!(slide.reveal_count, 0);
                for step in [0, 1, usize::MAX] {
                    assert!(matches!(slide.html_at_step(step), Cow::Borrowed(_)));
                    assert_eq!(slide.html_at_step(step), slide.html);
                }
                assert!(!slide.html.contains("data-reveal-step"));
                assert!(!slide.html.contains("data-reveal-pending"));
            }
        }
        let deck = parse_deck("# Title\n\nParagraph\n\n- One\n- Two").unwrap();
        assert_eq!(
            deck.slides[0].html,
            "<h1>Title</h1>\n<p>Paragraph</p>\n<ul>\n<li>One</li>\n<li>Two</li>\n</ul>\n"
        );
    }

    #[test]
    fn ide_metadata_renders_only_on_the_wrapper() {
        let url = "ZeD://file/tmp/a%20b.rs?line=12&column=3#symbol%22";
        for language in ["rust", "rs", "python"] {
            let source = format!("```{language} ide=\"{url}\"\nhello\n```");
            let html = &parse_deck(&source).unwrap().slides[0].html;
            assert!(html.contains("class=\"rust-code\""));
            assert_eq!(html.contains("data-rust-code"), language != "python");
            assert!(html.contains(
                "data-code-ide-url=\"ZeD://file/tmp/a%20b.rs?line=12&amp;column=3#symbol%22\""
            ));
            let pre = &html[html.find("<pre").unwrap()..html.find("</pre>").unwrap()];
            assert!(!pre.contains("ide="));
            assert!(!pre.contains(url));
            assert!(pre.contains("hello"));
        }
        for language in ["rust", "python", "mermaid"] {
            let source = format!("```{language}\nhello\n```");
            let html = &parse_deck(&source).unwrap().slides[0].html;
            assert!(!html.contains("data-code-ide-url"));
            assert_eq!(html.contains("rust-code"), language == "rust");
        }
        assert_eq!(
            parse_code_fence_info("rust unrelated info")
                .unwrap()
                .language,
            "rust"
        );
    }

    #[test]
    fn ide_metadata_allows_only_editor_schemes() {
        for scheme in [
            "zed",
            "vscode",
            "vscode-insiders",
            "idea",
            "pycharm",
            "clion",
            "goland",
            "rustrover",
            "webstorm",
            "phpstorm",
            "rider",
            "rubymine",
            "datagrip",
            "jetbrains",
        ] {
            let info = format!(
                "rust ide=\"{}://file/a%20b?line=1#main\"",
                scheme.to_uppercase()
            );
            assert!(parse_code_fence_info(&info).is_ok(), "{info}");
        }
        for url in [
            "javascript:alert(1)",
            "data:text/html,test",
            "file:///tmp/a",
            "unknown:a",
            "https://example.com",
            "",
            "zed:",
            "zed://a b",
            "zed://a\tb",
            "zed://a\u{7f}",
            "zed://a\0",
            "zed://a\"b",
            "zed://a'b",
            "zed://a<b",
            "zed://a>b",
            "zed://a\\b",
            "zed://a`b",
        ] {
            let info = format!("rust ide=\"{url}\"");
            assert!(parse_code_fence_info(&info).is_err(), "{info:?}");
            assert!(
                parse_deck(&format!("```{info}\nhello\n```")).is_err(),
                "{info:?}"
            );
        }
    }

    #[test]
    fn ide_metadata_rejects_malformed_duplicate_and_mermaid_attributes() {
        for info in [
            "rust ide",
            "rust ide=zed://file/a",
            "rust ide='zed://file/a'",
            "rust ide=\"zed://file/a",
            "rust ide = \"zed://file/a\"",
            "rust ide=\"zed://file/a\"junk",
            "rust ide=\"zed://a\" ide=\"vscode://b\"",
            "rust code/a.rs ide=\"zed://a\" ide=\"zed://b\"",
            "mermaid ide=\"zed://a\"",
            "MERMAID code/a.rs ide=\"zed://a\"",
            "ide=\"zed://a\"",
        ] {
            let error = parse_deck(&format!("```{info}\n```")).unwrap_err();
            assert!(
                format!("{error:#}").to_lowercase().contains("ide"),
                "{info}: {error:#}"
            );
        }
        assert!(parse_deck("> ```rust ide=\"javascript:bad\"\n> hello\n> ```").is_err());
    }

    #[test]
    fn legacy_code_references_preserve_ide_metadata() {
        let source = "```python code/word-count/python/step_01.py ide=\"vscode://file/a%20b?line=2&column=1#main\"\n```";
        let resolved = resolve_code_references(source).unwrap();
        assert!(
            resolved.starts_with("```python ide=\"vscode://file/a%20b?line=2&column=1#main\"\n")
        );
        assert!(!resolved.contains("code/word-count"));
        let html = &parse_deck(source).unwrap().slides[0].html;
        assert!(html.contains("data-code-ide-url="));
        assert!(!html.contains("data-rust-code"));
        assert!(html.contains("count_words"));
        assert_eq!(*html, parse_deck(&resolved).unwrap().slides[0].html);
    }

    #[test]
    fn renders_mermaid_blocks_as_safe_client_side_diagrams() {
        let deck = parse_deck(
            "```mermaid\nflowchart LR\n    A[<script>alert('no')</script>] --> B[Safe]\n```",
        )
        .unwrap();
        let html = &deck.slides[0].html;

        assert!(html.contains("data-mermaid-diagram"));
        assert!(html.contains("data-mermaid-source"));
        assert!(html.contains("data-mermaid-output"));
        assert!(html.contains("&lt;script&gt;"));
        assert!(!html.contains("<script>"));
    }

    #[test]
    fn highlights_code_with_catppuccin_mocha() {
        let html = highlight_code(
            "rust",
            "async fn main() { let string = \"mocha\"; let number = 42; }\n",
        );

        assert!(html.contains("#cba6f7"));
        assert!(html.contains("#a6e3a1"));
        assert!(html.contains("#fab387"));
        assert!(html.contains("data-rust-code"));
        assert!(!highlight_code("python", "print('hello')\n").contains("data-rust-code"));
    }

    #[test]
    fn parses_slides_and_poll() {
        let deck = parse_deck(
            "# Hello\n\n---\n\n# Vote\n\n:::poll question=\"Language?\" multiple orientation=\"vertical\"\n- Rust\n- Go\n:::",
        )
        .unwrap();
        assert_eq!(deck.slides.len(), 2);
        assert!(matches!(
            deck.slides[1].interaction,
            Some(Interaction::Poll {
                multiple: true,
                orientation: ChartOrientation::Vertical,
                ..
            })
        ));
    }

    #[test]
    fn collects_exactly_the_mermaid_blocks_that_are_rendered() {
        let deck = parse_deck(
            "# Diagrams\n\n> ~~~MeRmAiD\n> flowchart LR\n> A --> B\n> ~~~\n\n- Example\n\n  ```mermaid\n  sequenceDiagram\n  A->>B: hello\n  ```\n\n````markdown\n```mermaid\nnot a diagram\n```\n````\n\n    ```mermaid\n    also just code\n    ```\n\n<!--\n```mermaid\nnot rendered as a diagram\n```\n-->\n\n:::notes\n```mermaid\npie\n\"Yes\": 1\n```\n:::"
        ).unwrap();
        let slide = &deck.slides[0];
        assert_eq!(
            slide.mermaid_diagrams,
            [
                "flowchart LR\nA --> B\n",
                "sequenceDiagram\nA->>B: hello\n",
                "pie\n\"Yes\": 1\n",
            ]
        );
        assert_eq!(slide.html.matches("data-mermaid-diagram").count(), 2);
        assert_eq!(
            slide
                .notes
                .as_ref()
                .unwrap()
                .matches("data-mermaid-diagram")
                .count(),
            1
        );
    }

    #[test]
    fn kitchen_sink_example_covers_every_interaction() {
        let deck = parse_deck(include_str!("../examples/kitchen-sink.md")).unwrap();

        assert_eq!(deck.slides.len(), 16);
        assert_eq!(
            deck.slides
                .iter()
                .filter(|slide| matches!(slide.interaction, Some(Interaction::Poll { .. })))
                .count(),
            3
        );
        assert_eq!(
            deck.slides
                .iter()
                .filter(|slide| matches!(slide.interaction, Some(Interaction::WordCloud { .. })))
                .count(),
            1
        );
        assert_eq!(
            deck.slides
                .iter()
                .filter(|slide| matches!(slide.interaction, Some(Interaction::Quiz { .. })))
                .count(),
            1
        );
        assert_eq!(
            deck.slides
                .iter()
                .filter(|slide| matches!(slide.interaction, Some(Interaction::Ordering { .. })))
                .count(),
            1
        );
        assert!(matches!(
            deck.slides[7].interaction,
            Some(Interaction::Poll {
                orientation: ChartOrientation::Vertical,
                ..
            })
        ));
        assert!(matches!(
            deck.slides[8].interaction,
            Some(Interaction::Poll { multiple: true, .. })
        ));
        assert!(
            deck.slides
                .iter()
                .any(|slide| slide.html.contains("data-mermaid-diagram"))
        );
    }

    #[test]
    fn intro_to_rust_example_parses() {
        let deck = parse_deck(include_str!("../examples/intro-to-rust.md")).unwrap();

        assert!(!deck.slides.is_empty());
        assert!(
            deck.slides
                .iter()
                .any(|slide| matches!(slide.interaction, Some(Interaction::Poll { .. })))
        );
        assert!(
            deck.slides
                .iter()
                .any(|slide| matches!(slide.interaction, Some(Interaction::WordCloud { .. })))
        );
    }

    #[test]
    fn parses_ordering_cards() {
        let deck = parse_deck(
            ":::ordering prompt=\"Put the release steps in order\"\n- Build\n- Test\n- Deploy\n:::",
        )
        .unwrap();

        assert!(matches!(
            &deck.slides[0].interaction,
            Some(Interaction::Ordering { prompt, options })
                if prompt == "Put the release steps in order" && options.len() == 3
        ));
    }

    #[test]
    fn parses_sanitized_presenter_notes_separately_from_slide_content() {
        let deck = parse_deck(
            "# Ownership\n\n:::notes\nRemind everyone about **moves**.\n\n<script>alert('no')</script>\n:::",
        )
        .unwrap();
        let slide = &deck.slides[0];

        assert!(slide.html.contains("<h1>Ownership</h1>"));
        assert!(!slide.html.contains("Remind everyone"));
        let notes = slide.notes.as_deref().unwrap();
        assert!(notes.contains("<strong>moves</strong>"));
        assert!(!notes.contains("<script>"));
    }

    #[test]
    fn parses_sandboxed_local_iframes_in_content_order() {
        let deck = parse_deck(
            "# Before\n\n:::iframe src=\"/assets/embeds/demo/index.html?step=1#example\" title=\"Interactive & accessible\"\n:::\n\nAfter the demo.\n\n:::poll\n- Yes\n- No\n:::"
        )
        .unwrap();
        let slide = &deck.slides[0];

        let heading = slide.html.find("<h1>Before</h1>").unwrap();
        let iframe = slide.html.find("<iframe").unwrap();
        let after = slide.html.find("After the demo.").unwrap();
        assert!(heading < iframe && iframe < after);
        assert!(slide.html.contains("id=\"slide-iframe-1-1\""));
        assert!(
            slide
                .html
                .contains("src=\"/assets/embeds/demo/index.html?step=1#example\"")
        );
        assert!(
            slide
                .html
                .contains("title=\"Interactive &amp; accessible\"")
        );
        assert!(slide.html.contains("sandbox=\"allow-scripts\""));
        assert!(!slide.html.contains("allow-same-origin"));
        assert_eq!(slide.iframe_assets, ["embeds/demo/index.html"]);
        assert!(slide.interaction.is_some());
    }

    #[test]
    fn accepts_wrapped_and_self_closing_iframe_directives() {
        for source in [
            "# Architecture under review\n\n:::iframe src=\"/assets/embeds/kgdb-architecture/index.html\"\ntitle=\"Interactive KGDB application architecture\"\n:::",
            "# Architecture under review\n\n:::iframe src=\"/assets/embeds/kgdb-architecture/index.html\" title=\"Interactive KGDB application architecture\" :::",
        ] {
            let deck = parse_deck(source).unwrap();
            let slide = &deck.slides[0];

            assert!(slide.html.contains("<iframe"));
            assert!(!slide.html.contains(":::iframe"));
            assert_eq!(slide.iframe_assets, ["embeds/kgdb-architecture/index.html"]);
        }
    }

    #[test]
    fn iframe_directives_preserve_whole_slide_markdown_semantics() {
        let deck = parse_deck(
            "[Link defined later][reference]\n\n:::iframe src=\"/assets/embeds/demo/index.html\" title=\"Demo\"\n:::\n\n[reference]: https://example.com",
        )
        .unwrap();

        assert!(deck.slides[0].html.contains("href=\"https://example.com\""));
        assert!(deck.slides[0].html.contains("<iframe"));
    }

    #[test]
    fn rejects_unsafe_or_inaccessible_iframe_directives() {
        for source in [
            ":::iframe title=\"Missing source\"\n:::",
            ":::iframe src=\"/assets/embeds/demo/index.html\"\n:::",
            ":::iframe src=\"/assets/embeds/demo/index.html\" title=\"\"\n:::",
            ":::iframe src=\"https://example.com/demo.html\" title=\"External\"\n:::",
            ":::iframe src=\"//example.com/demo.html\" title=\"External\"\n:::",
            ":::iframe src=\"/assets/demo.html\" title=\"Outside embeds\"\n:::",
            ":::iframe src=\"/assets/embeds/../secret.html\" title=\"Traversal\"\n:::",
            ":::iframe src=\"/assets/embeds/demo/%2e%2e/secret.html\" title=\"Encoded traversal\"\n:::",
            ":::iframe src=\"/assets/embeds/demo:name/index.html\" title=\"Unsafe filename\"\n:::",
            ":::iframe src=\"/assets/embeds/demo/image.png\" title=\"Not HTML\"\n:::",
            ":::iframe src=\"/assets/embeds/demo/index.html\" title=\"Body\"\nnot allowed\n:::",
        ] {
            let error = parse_deck(source).unwrap_err();
            assert!(error.to_string().contains("slide 1"), "{error:#}");
        }
    }

    #[test]
    fn ignores_iframe_markers_inside_code_blocks() {
        for source in [
            "```markdown\n:::iframe src=\"/assets/embeds/demo/index.html\" title=\"Example\"\n:::\n```",
            "    :::iframe src=\"/assets/embeds/demo/index.html\" title=\"Example\"\n    :::",
        ] {
            let deck = parse_deck(source).unwrap();

            assert!(deck.slides[0].iframe_assets.is_empty());
            assert!(deck.slides[0].html.contains(":::iframe"));
            assert!(!deck.slides[0].html.contains("<iframe"));
        }
    }

    #[test]
    fn presenter_notes_can_coexist_with_an_interaction() {
        let deck = parse_deck(
            ":::poll\n- Rust\n- Go\n:::\n\n:::notes\nAsk for a show of hands first.\n:::",
        )
        .unwrap();

        assert!(deck.slides[0].interaction.is_some());
        assert!(deck.slides[0].notes.is_some());
    }

    #[test]
    fn validates_presenter_notes_blocks() {
        for source in [
            ":::notes speaker=\"me\"\nNo arguments.\n:::",
            ":::notes\nFirst\n:::\n:::notes\nSecond\n:::",
            ":::notes\nMissing close",
        ] {
            let error = parse_deck(source).unwrap_err();
            assert!(error.to_string().contains("slide 1"));
        }
    }

    #[test]
    fn presenter_notes_keep_fence_protection_inside_html_blocks() {
        for body in [
            "<div>Example</div>\n```text\n:::\n```\nSECRET",
            "<div>Example</div>\n~~~text\n:::reveal\n:::\n~~~\nSECRET",
            "<div>Example</div>\n````text\n```\n:::\n````\nSECRET",
        ] {
            for suffix in ["", "\n\n:::reveal\nPublic reveal\n:::"] {
                let source = format!("# Public\n\n:::notes\n{body}\n:::{suffix}");
                let deck = parse_deck(&source).unwrap();
                let slide = &deck.slides[0];
                assert!(slide.notes.as_ref().unwrap().contains("SECRET"));
                assert!(!slide.html.contains("SECRET"));
                assert!(slide.html.contains("<h1>Public</h1>"));
                assert_eq!(slide.reveal_count, usize::from(!suffix.is_empty()));
                assert!(!slide.html_at_step(0).contains("SECRET"));
                if suffix.is_empty() {
                    assert_eq!(slide.html, "<h1>Public</h1>\n");
                } else {
                    assert!(
                        slide
                            .html
                            .contains("<p data-reveal-step=\"1\">Public reveal</p>")
                    );
                }
            }
        }
    }

    #[test]
    fn presenter_notes_with_unclosed_html_hidden_fences_fail_closed() {
        for fence in ["```", "~~~"] {
            let source =
                format!("# Public\n\n:::notes\n<div>Example</div>\n{fence}text\n:::\nSECRET");
            let error = parse_deck(&source).unwrap_err();
            assert!(
                format!("{error:#}").contains("presenter notes block is missing its closing :::")
            );
        }
    }

    #[test]
    fn nested_code_fences_do_not_swallow_following_notes_or_reveals() {
        let deck = parse_deck(
            "- ```markdown\n  :::reveal\n  Example\n  :::\n  ```\n\n:::notes\nSECRET\n:::\n\n:::reveal\nPublic reveal\n:::",
        )
        .unwrap();
        let slide = &deck.slides[0];
        assert!(slide.notes.as_ref().unwrap().contains("SECRET"));
        assert!(!slide.html.contains("SECRET"));
        assert_eq!(slide.reveal_count, 1);
        assert!(
            slide
                .html
                .contains("<p data-reveal-step=\"1\">Public reveal</p>")
        );
    }

    #[test]
    fn ignores_presenter_notes_markers_inside_code_fences() {
        let deck = parse_deck("```markdown\n:::notes\nNot notes\n:::\n```").unwrap();

        assert!(deck.slides[0].notes.is_none());
        assert!(deck.slides[0].html.contains(":::notes"));
    }

    #[test]
    fn strips_raw_html() {
        let deck = parse_deck(
            "<script>alert(1)</script><iframe src=\"/assets/embeds/demo/index.html\"></iframe>",
        )
        .unwrap();
        assert!(!deck.slides[0].html.contains("<script>"));
        assert!(!deck.slides[0].html.contains("<iframe"));
    }

    #[test]
    fn ignores_slide_and_interaction_markers_inside_code_fences() {
        let deck =
            parse_deck("```text\n---\n:::poll\n- one\n- two\n:::\n```\n\n---\n\n# Second").unwrap();
        assert_eq!(deck.slides.len(), 2);
        assert!(deck.slides[0].interaction.is_none());
        assert!(deck.slides[0].html.contains(":::poll"));
    }

    #[test]
    fn resolves_code_files_inside_the_presentation_code_directory() {
        let source = "```python code/word-count/python/step_01.py\n```";

        let resolved = resolve_code_references(source).unwrap();
        let deck = parse_deck(source).unwrap();

        assert!(resolved.starts_with("```python\n"));
        assert!(resolved.contains("def count_words(filename):"));
        assert!(!resolved.contains("code/word-count"));
        assert!(deck.slides[0].html.contains("count_words"));
    }

    #[test]
    fn code_references_reject_inline_content_and_path_traversal() {
        let inline = "```python code/word-count/python/step_01.py\nprint('ambiguous')\n```";
        let traversal = "```text code/../intro-to-rust.md\n```";

        assert!(
            resolve_code_references(inline)
                .unwrap_err()
                .to_string()
                .contains("cannot also contain inline code")
        );
        assert!(
            resolve_code_references(traversal)
                .unwrap_err()
                .to_string()
                .contains("must stay inside the code/ directory")
        );
    }

    #[test]
    fn code_reference_errors_identify_the_slide() {
        let source = "# First\n\n---\n\n```rust code/word-count/rust/does-not-exist.rs\n```";

        let error = parse_deck(source).unwrap_err();

        assert!(error.to_string().contains("slide 2"));
    }

    #[test]
    fn secures_links_and_opens_external_destinations_in_a_new_tab() {
        let deck = parse_deck(
            "[unsafe](javascript:alert(1)) [external](https://example.com) [local](/join)",
        )
        .unwrap();
        let html = &deck.slides[0].html;

        assert!(!html.contains("javascript:"));
        assert!(html.contains(
            "href=\"https://example.com\" target=\"_blank\" rel=\"noopener noreferrer\""
        ));
        assert!(html.contains("href=\"/join\">local</a>"));
    }

    #[test]
    fn zed_links_remain_clickable_but_are_not_image_sources() {
        for url in [
            "zed://file/Users/example/project/main.rs:12:3",
            "ZED://file/Users/example/My%20Project/main.rs",
            "zed:///agent/skill?name=presentation&source=global",
        ] {
            let source = format!(
                "[Open in Zed](<{url}>)\n\n![Not an image](<{url}>)\n\n:::notes\n[Notes link](<{url}>)\n:::"
            );
            let deck = parse_deck(&source).unwrap();
            let destination = html_escape::encode_double_quoted_attribute(url);
            let link = format!("href=\"{destination}\"");
            assert!(deck.slides[0].html.contains(&link));
            assert!(deck.slides[0].notes.as_ref().unwrap().contains(&link));
            assert!(deck.slides[0].html.contains("src=\"#\""));
            assert!(!deck.slides[0].html.contains("target=\"_blank\""));
        }
        let deck = parse_deck("[Other](zed-other:example) [Unsafe](javascript:alert(1))").unwrap();
        assert!(!deck.slides[0].html.contains("href=\"zed-other:"));
        assert!(!deck.slides[0].html.contains("href=\"javascript:"));
    }

    #[test]
    fn requires_exact_interaction_names() {
        let deck = parse_deck(":::poll-results\n- Rust\n- Go\n:::").unwrap();
        assert!(deck.slides[0].interaction.is_none());
        assert!(deck.slides[0].html.contains("poll-results"));
    }

    #[test]
    fn rejects_word_cloud_body_content() {
        let error = parse_deck(":::wordcloud\nunexpected\n:::").unwrap_err();
        assert!(error.to_string().contains("slide 1"));
    }

    #[test]
    fn poll_questions_are_optional_and_horizontal_by_default() {
        for source in [
            ":::poll\n- Coffee\n- Beer\n:::",
            ":::poll question=\"\"\n- Coffee\n- Beer\n:::",
        ] {
            let deck = parse_deck(source).unwrap();
            assert!(matches!(
                &deck.slides[0].interaction,
                Some(Interaction::Poll {
                    question: None,
                    orientation: ChartOrientation::Horizontal,
                    ..
                })
            ));
        }
    }

    #[test]
    fn interaction_arguments_follow_the_declared_grammar() {
        for source in [
            ":::poll notquestion=\"Wrong\"\n- Rust\n- Go\n:::",
            ":::poll orientation=vertical\n- Rust\n- Go\n:::",
            ":::wordcloud max=abc\n:::",
        ] {
            let error = parse_deck(source).unwrap_err();
            assert!(error.to_string().contains("slide 1"));
        }

        let deck =
            parse_deck(":::poll question=\"Choose multiple values\"\n- Rust\n- Go\n:::").unwrap();
        assert!(matches!(
            deck.slides[0].interaction,
            Some(Interaction::Poll {
                multiple: false,
                ..
            })
        ));
    }

    #[test]
    fn nested_poll_options_do_not_count() {
        let error = parse_deck(":::poll\n- Rust\n  - nested\n:::").unwrap_err();
        assert!(error.to_string().contains("slide 1"));
    }
}
